Repository florentianayuwono/DigitalIT, pull requests merged in 2022-07, with the labels that each got.

#27 Backend improve
  backend/controllers/businessController.js
  backend/routes/businessRoutes.js
  frontend/src/config/RouteManager.js
Labels: enhancement

#28 Style change in /business
  frontend/src/components/BusinessItem.js
  frontend/src/pages/BusinessParticular/DisplayBusinessParticular.jsx
  frontend/src/pages/BusinessParticular/DisplayIndividualBusiness.jsx
  frontend/src/pages/Product/Products.jsx
Labels: enhancement, help wanted

#32 Improvement in UI and documentation
  backend/auxiliaries/helperFunctions.js
  backend/config/db.js
  backend/controllers/businessController.js
  backend/controllers/productController.js
  backend/controllers/storeController.js
  backend/controllers/userController.js
  backend/middlewares/authMiddleware.js
  backend/middlewares/errorMiddleware.js
  backend/routes/productRoutes.js
  backend/routes/storeRoutes.js
  backend/routes/userRoutes.js
  backend/server.js
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/src/App.js
  frontend/src/features/auth/authRoute.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/pages/Landing.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/Register.jsx
Labels: enhancement

#33 Frontend feature
  backend/controllers/productController.js
  frontend/src/config/RouteManager.js
  frontend/src/features/product/productContext.js
  frontend/src/features/product/productReducer.js
  frontend/src/features/product/productRoute.js
  frontend/src/features/product/productServices.js
  frontend/src/pages/BusinessParticular/DisplayBusinessParticular.jsx
  frontend/src/pages/BusinessParticular/DisplayIndividualBusiness.jsx
  frontend/src/pages/Product/Products.jsx
Labels: enhancement

#34 Dashboard UI improvement
  backend/controllers/userController.js
  frontend/src/components/Header.js
  frontend/src/features/auth/authServices.js
  frontend/src/index.css
  frontend/src/pages/Dashboard.jsx
  frontend/src/pages/Landing.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/Register.jsx
Labels: enhancement

#36 View Business UI Improvement
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/BusinessItem.js
  frontend/src/components/InputBusinessParticular.js
  frontend/src/features/auth/authReducer.js
  frontend/src/features/business/businessServices.js
  frontend/src/pages/BusinessParticular/DisplayBusinessParticular.jsx
  frontend/src/pages/Dashboard.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/Register.jsx
Labels: enhancement

#43 Frontend feature
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/InputBusinessParticular.js
  frontend/src/components/PopupMessageButton.js
  frontend/src/features/business/businessServices.js
  frontend/src/index.js
  frontend/src/pages/BusinessParticular/DisplayIndividualBusiness.jsx
  frontend/src/pages/Product/Products.jsx
  frontend/src/theme/components/button.js
  frontend/src/theme/index.js
  frontend/src/theme/styles.js
Labels: enhancement

#44 Database modification
  README.md
  backend/config/database.sql
  backend/controllers/businessController.js
  backend/controllers/platformController.js
  backend/controllers/productController.js
  backend/controllers/storeController.js
  backend/middlewares/authAdminMiddleware.js
  backend/readme.md
  backend/routes/platformRoutes.js
  backend/routes/productRoutes.js
  backend/routes/storeRoutes.js
  backend/server.js
  frontend/src/components/AddStoreForm.js
  frontend/src/components/BusinessItem.js
  frontend/src/components/InputBusinessParticular.js
  frontend/src/components/PopupMessageButton.js
  frontend/src/components/ProductSearchBar.js
  frontend/src/components/ProductSearchResultItem.js
  frontend/src/config/RouteManager.js
  frontend/src/features/auth/authServices.js
  frontend/src/features/business/businessServices.js
  frontend/src/features/platform/platformServices.js
  frontend/src/features/product/productReducer.js
  frontend/src/features/product/productServices.js
  frontend/src/features/store/storeServices.js
  frontend/src/pages/BusinessParticular/DisplayIndividualBusiness.jsx
  frontend/src/pages/Product/Products.jsx
  frontend/src/pages/Store/DisplayIndividualStore.js
  frontend/src/pages/Store/DisplayStores.js
  frontend/src/pages/Store/MainStoreLayoutPage.js
Labels: enhancement

#46 Input Sales Data
  backend/controllers/productController.js
  backend/controllers/storeController.js
  backend/routes/platformRoutes.js
  backend/routes/productRoutes.js
  frontend/src/components/PopupMessageButton.js
  frontend/src/components/ProductSearchBar.js
  frontend/src/components/ProductSearchResultItem.js
  frontend/src/config/RouteManager.js
  frontend/src/features/product/productReducer.js
  frontend/src/features/product/productServices.js
  frontend/src/features/store/storeServices.js
  frontend/src/pages/Dashboard.jsx
  frontend/src/pages/Product/AddProduct.jsx
  frontend/src/pages/Product/Products.jsx
  frontend/src/pages/Recommendation/InputProductSales.jsx
  frontend/src/pages/Recommendation/MainRecommendationPage.jsx
  frontend/src/pages/Recommendation/MyRecommendations.jsx
  frontend/src/pages/Store/DisplayStores.js
Labels: enhancement

#47 Business and Finance Recommendation Functions, Static Recommendation Page
  backend/auxiliaries/recommendationFunctions/businessRecommendationFunctions.js
  backend/auxiliaries/recommendationFunctions/financeRecommendationFunctions.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/features/auth/authServices.js
  frontend/src/features/business/businessServices.js
  frontend/src/features/platform/platformServices.js
  frontend/src/features/product/productServices.js
  frontend/src/features/store/storeServices.js
  frontend/src/index.js
  frontend/src/pages/Recommendation/MyRecommendations.jsx
  package-lock.json
  package.json
Labels: enhancement

#53 Frontend feature
  frontend/src/config/RouteManager.js
  frontend/src/index.js
  frontend/src/pages/Dashboard.jsx
  frontend/src/pages/Finance/FinanceRecommendations.jsx
  frontend/src/pages/Finance/FinanceTrackingInput.jsx
  frontend/src/pages/Finance/InputExpenseForm.jsx
  frontend/src/pages/Finance/InputTrialBalanceForm.jsx
  frontend/src/pages/Finance/MainFinancePage.jsx
  frontend/src/pages/Finance/MyFinance.jsx
  frontend/src/theme/index.js
  frontend/src/theme/styles.js
Labels: enhancement

#54 Frontend feature
  backend/controllers/businessController.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/BusinessSummary.js
  frontend/src/config/RouteManager.js
  frontend/src/features/business/businessReducer.js
  frontend/src/features/business/businessServices.js
  frontend/src/features/product/productReducer.js
  frontend/src/features/product/productServices.js
  frontend/src/pages/Login.jsx
  frontend/src/pages/Recommendation/InputProductSales.jsx
  frontend/src/pages/Recommendation/MainRecommendationPage.jsx
  frontend/src/pages/Recommendation/MyRecommendations.jsx
Labels: enhancement

#56 Frontend feature
  backend/auxiliaries/productRecommendationFunctions.js
  backend/auxiliaries/recommendationFunctions/businessRecommendationFunctions.js
  backend/controllers/businessController.js
  backend/routes/businessRoutes.js
  frontend/src/components/BusinessRecommendations/SuitablePlatform.js
  frontend/src/components/InputBusinessParticular.js
  frontend/src/config/RouteManager.js
  frontend/src/features/business/businessServices.js
  frontend/src/features/product/productServices.js
  frontend/src/pages/Product/AddProduct.jsx
  frontend/src/pages/Recommendation/BusinessSummaryPage.jsx
  frontend/src/pages/Recommendation/MyRecommendations.jsx
Labels: enhancement

#57 Frontend feature
  backend/controllers/businessController.js
  backend/controllers/storeController.js
  frontend/src/components/AddStoreForm.js
  frontend/src/components/BusinessRecommendations/ExploitPopularity.js
  frontend/src/components/BusinessRecommendations/StartDigitalizing.js
  frontend/src/components/BusinessSummary.js
  frontend/src/config/RouteManager.js
  frontend/src/features/business/businessReducer.js
  frontend/src/features/store/storeServices.js
  frontend/src/pages/BusinessParticular/DisplayBusinessParticular.jsx
  frontend/src/pages/Recommendation/BusinessSummaryPage.jsx
  frontend/src/pages/Recommendation/MainRecommendationPage.jsx
  frontend/src/pages/Recommendation/MyRecommendations.jsx
  frontend/src/pages/Recommendation/ProductRecommendationsPage.jsx
  frontend/src/pages/Register.jsx
  frontend/src/pages/Store/DisplayStores.js
Labels: enhancement

#58 Product Recommendations Page
  backend/controllers/productController.js
  frontend/src/components/BusinessRecommendations/StartDigitalizing.js
  frontend/src/features/product/productServices.js
  frontend/src/pages/Recommendation/ProductRecommendationsPage.jsx
Labels: enhancement

#60 Finance Recommendation Static Page
  frontend/src/features/business/businessServices.js
  frontend/src/features/product/productServices.js
  frontend/src/features/store/storeServices.js
  frontend/src/pages/Finance/FinanceRecommendations.jsx
  frontend/src/pages/Finance/MainFinancePage.jsx
  frontend/src/pages/Finance/MyFinance.jsx
  frontend/src/pages/Product/Products.jsx
Labels: enhancement

#61 Neater input form
  frontend/src/components/BusinessSummary.js
  frontend/src/pages/Finance/FinanceRecommendations.jsx
  frontend/src/pages/Finance/InputExpenseForm.jsx
  frontend/src/pages/Finance/InputTrialBalanceForm.jsx
  frontend/src/pages/Finance/MainFinancePage.jsx
  frontend/src/pages/Recommendation/BusinessSummaryPage.jsx
  frontend/src/pages/Recommendation/InputProductSales.jsx
  frontend/src/pages/Recommendation/MainRecommendationPage.jsx
  frontend/src/pages/Recommendation/ProductRecommendationsPage.jsx
Labels: enhancement

#68 Frontend feature bug fix
  backend/controllers/businessController.js
  backend/controllers/productController.js
  frontend/src/pages/Recommendation/BusinessSummaryPage.jsx
  frontend/src/pages/Recommendation/MainRecommendationPage.jsx
Labels: bug

#69 Fixed bug where we can't use the browser's back button. Improved add business feature.
  frontend/src/components/InputBusinessParticular.js
  frontend/src/config/RouteManager.js
  frontend/src/pages/Finance/FinanceTrackingInput.jsx
  frontend/src/pages/Finance/MainFinancePage.jsx
  frontend/src/pages/Recommendation/BusinessSummaryPage.jsx
Labels: bug, enhancement

#70 Refactor and fixed dateRangeParser function, fixed a few messages.
  backend/auxiliaries/helperFunctions.js
  backend/controllers/productController.js
  frontend/src/features/product/productServices.js
Labels: bug, enhancement

#71 Very minor bug fix for business summary API
  backend/controllers/businessController.js
Labels: bug

#72 Frontend: Fully renovated add business form.
  frontend/src/components/InputBusinessParticular.js
  frontend/src/features/product/productServices.js
  frontend/src/features/store/storeServices.js
Labels: bug, enhancement

#74 Minor UI improvements
  frontend/src/App.js
  frontend/src/components/Footer.js
  frontend/src/components/InputBusinessParticular.js
  frontend/src/components/ProductSearchBar.js
  frontend/src/pages/BusinessParticular/DisplayBusinessParticular.jsx
  frontend/src/pages/Dashboard.jsx
  frontend/src/pages/Landing.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/Product/AddProduct.jsx
  frontend/src/pages/Register.jsx
Labels: enhancement
